// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3TiVdGgg82DB2aDqavf-JOV6PVaq49jw',
    appId: '1:795339981839:web:e599bd7cdaba7109048f7a',
    messagingSenderId: '795339981839',
    projectId: 'fluttershop-c33a9',
    authDomain: 'fluttershop-c33a9.firebaseapp.com',
    storageBucket: 'fluttershop-c33a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJk-hcVwpusgYohziLWxrVMu-4CW3J0As',
    appId: '1:795339981839:android:5f9dd3eee9d2a84c048f7a',
    messagingSenderId: '795339981839',
    projectId: 'fluttershop-c33a9',
    storageBucket: 'fluttershop-c33a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8wYJzo4VFsl00O6mD6KsOnfe6fxkbUIE',
    appId: '1:795339981839:ios:2edc33a22e5f0daf048f7a',
    messagingSenderId: '795339981839',
    projectId: 'fluttershop-c33a9',
    storageBucket: 'fluttershop-c33a9.appspot.com',
    iosBundleId: 'com.example.shoesShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8wYJzo4VFsl00O6mD6KsOnfe6fxkbUIE',
    appId: '1:795339981839:ios:2edc33a22e5f0daf048f7a',
    messagingSenderId: '795339981839',
    projectId: 'fluttershop-c33a9',
    storageBucket: 'fluttershop-c33a9.appspot.com',
    iosBundleId: 'com.example.shoesShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3TiVdGgg82DB2aDqavf-JOV6PVaq49jw',
    appId: '1:795339981839:web:02c220fcf8dd2cc8048f7a',
    messagingSenderId: '795339981839',
    projectId: 'fluttershop-c33a9',
    authDomain: 'fluttershop-c33a9.firebaseapp.com',
    storageBucket: 'fluttershop-c33a9.appspot.com',
  );
}
