name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_HOME: /opt/hostedtoolcache/flutter

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.1' 

    - name: Flutter pub get
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Check code formatting
      run: flutter format --set-exit-if-changed .

    - name: Run unit tests
      run: flutter test

    - name: Generate golden files
      run: flutter test --update-goldens

    - name: Run widget tests
      run: flutter test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results
