name: Flutter CI/CD

on:
  push:
    branches:
      - new_main  
  pull_request:
    branches:
      - new_main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'  

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  golden_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Run golden tests
        run: flutter test test/golden_tests.dart

  deploy_to_firebase:
    runs-on: ubuntu-latest
    needs: golden_tests 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Firebase CLI
        uses: w9jds/firebase-action@v2
        with:
          firebase-version: '9.14.0'  

      - name: Login to Firebase
        run: firebase login:ci --token "${{AIzaSyAJk-hcVwpusgYohziLWxrVMu-4CW3J0As}}"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting

